[package]
name = "snake_gg_ez"
version = "0.0.1"
authors = ["jkomoroski <jkomoroski@alianza.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
rand = "0.7"