# Window
grid_width = 30
grid_height = 30
cell_width = 16
cell_height = 16

# Clock
updates_per_second = 8.0

#Colors
background = [0.2, 0.13, 0.0, 1.0]
snake_head = [1.0, 0.5, 0.0, 1.0]
snake_body = [0.0, 0.33, 0.15, 1.0]
food = [0.0, 0.0, 1.0, 1.0]